services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sudoku_2077
    ports:
      - "5432:5432"
    volumes:
      - sudoku_postgres_data:/var/lib/postgresql/data

volumes:
  sudoku_postgres_data:
